### ISSUE TITLE
Broken with 'Walls Approach' update

### ISSUE THREAD

**Issue by God-damnit-all** [CuriousNekomimi/AIDCAT#14]
https://latitude.io/blog/the-walls-approach

It seems they're now encrypting user stories. When I try to download them with AIDCAT, I get 400 Bad Request. I might have missed my chance, unless this script can be updated to decrypt the stories.

**Comment by Moist-Cat** [comment]
No, the adventures don't seem to be encrypted. They probably made a minor change that broke the script (which is not being maintained anymore).
I will look into it and see if I can help you out.

**Comment by God-damnit-all** [comment]
> No, the adventures don't seem to be encrypted. They probably made a minor change that broke the script (which is not being maintained anymore). I will look into it and see if I can help you out.

Thanks.

**Comment by Moist-Cat** [comment]
@ImportTaste 
Here.
https://github.com/Moist-Cat/AIDScrapper

    pip3 install aids
    python3 -m aids all -p aid

It took longer than I thought, heh.

**Comment by God-damnit-all** [comment]
Thanks! Having an issue, though...
```
C:\>aids-windows.bat help
NAME
    aids  - a client made to interact with the different dynamic storytelling services. It\'s main feature consist in downloading and converting stories to be utilized in all the other platforms or to read them locally.

SYNOPSIS
    python manage.py [publish/stories/scenarios/makenai/makejson/fenix/register/all_to_html/test] [-t/--title title] [-a/--actions actions] [-p/--platform platform] [expression]

COMMANDS
    stories        Downloads stories.

    scenarios      Download scenarios

    all            Dowloads all of the above

    publish        Publish a scenario from scenarios.json (XXX) Out of service.

    makenai        Transform all scenarios in the scenario.json file to *.scenario files - fully compatible with NAI and Holo.

    makejson       Transform all *.scenario files to the AID format and dumps it into the scenario.json file.

    fenix          Posts all your stuff (stored in the .json) on your account. Does not include WI due to changes in AID back-end.
    alltohtml      Transform all objects in their respective .json file and dumps them in form of human-friendly html files.

    test           Run the tests suite. It only covers part the application layer -- anything else would require an account and credentials.

    register       Register credentials to use with the tool.

COMMAND LINE OPTIONS
    -a             Minimal actions that all downloaded stories must have.

    -t             Title that the queries object must have.

    -p             Platform to where the client must point to.


C:\>aids-windows.bat all
all is not a valid command

C:\>aids-windows.bat fenix
fenix is not a valid command

C:\>aids-windows.bat stories
stories is not a valid command
```
Am I missing something? aids-windows.bat register works, but that's about it.

**Comment by God-damnit-all** [comment]
By the way, was the world info for the worlds that are for sale on AI Dungeon ever successfully extracted (meaning all the entries, not just the description), or has that always been impossible? If it has, is it posted up anywhere?

**Comment by Moist-Cat** [comment]
> Thanks! Having an issue, though...
> 
> ```
> C:\>aids-windows.bat help
> NAME
>     aids  - a client made to interact with the different dynamic storytelling services. It\'s main feature consist in downloading and converting stories to be utilized in all the other platforms or to read them locally.
> 
> SYNOPSIS
>     python manage.py [publish/stories/scenarios/makenai/makejson/fenix/register/all_to_html/test] [-t/--title title] [-a/--actions actions] [-p/--platform platform] [expression]
> 
> COMMANDS
>     stories        Downloads stories.
> 
>     scenarios      Download scenarios
> 
>     all            Dowloads all of the above
> 
>     publish        Publish a scenario from scenarios.json (XXX) Out of service.
> 
>     makenai        Transform all scenarios in the scenario.json file to *.scenario files - fully compatible with NAI and Holo.
> 
>     makejson       Transform all *.scenario files to the AID format and dumps it into the scenario.json file.
> 
>     fenix          Posts all your stuff (stored in the .json) on your account. Does not include WI due to changes in AID back-end.
>     alltohtml      Transform all objects in their respective .json file and dumps them in form of human-friendly html files.
> 
>     test           Run the tests suite. It only covers part the application layer -- anything else would require an account and credentials.
> 
>     register       Register credentials to use with the tool.
> 
> COMMAND LINE OPTIONS
>     -a             Minimal actions that all downloaded stories must have.
> 
>     -t             Title that the queries object must have.
> 
>     -p             Platform to where the client must point to.
> 
> 
> C:\>aids-windows.bat all
> all is not a valid command
> 
> C:\>aids-windows.bat fenix
> fenix is not a valid command
> 
> C:\>aids-windows.bat stories
> stories is not a valid command
> ```
> 
> Am I missing something? aids-windows.bat register works, but that's about it.

The platform is a required param. You need to point it to the right website.
I should have made it clearer, my bad.

    aids-windows.bat all -p aid

**Comment by God-damnit-all** [comment]
> > Thanks! Having an issue, though...
> > ```
> > C:\>aids-windows.bat help
> > NAME
> >     aids  - a client made to interact with the different dynamic storytelling services. It\'s main feature consist in downloading and converting stories to be utilized in all the other platforms or to read them locally.
> > 
> > SYNOPSIS
> >     python manage.py [publish/stories/scenarios/makenai/makejson/fenix/register/all_to_html/test] [-t/--title title] [-a/--actions actions] [-p/--platform platform] [expression]
> > 
> > COMMANDS
> >     stories        Downloads stories.
> > 
> >     scenarios      Download scenarios
> > 
> >     all            Dowloads all of the above
> > 
> >     publish        Publish a scenario from scenarios.json (XXX) Out of service.
> > 
> >     makenai        Transform all scenarios in the scenario.json file to *.scenario files - fully compatible with NAI and Holo.
> > 
> >     makejson       Transform all *.scenario files to the AID format and dumps it into the scenario.json file.
> > 
> >     fenix          Posts all your stuff (stored in the .json) on your account. Does not include WI due to changes in AID back-end.
> >     alltohtml      Transform all objects in their respective .json file and dumps them in form of human-friendly html files.
> > 
> >     test           Run the tests suite. It only covers part the application layer -- anything else would require an account and credentials.
> > 
> >     register       Register credentials to use with the tool.
> > 
> > COMMAND LINE OPTIONS
> >     -a             Minimal actions that all downloaded stories must have.
> > 
> >     -t             Title that the queries object must have.
> > 
> >     -p             Platform to where the client must point to.
> > 
> > 
> > C:\>aids-windows.bat all
> > all is not a valid command
> > 
> > C:\>aids-windows.bat fenix
> > fenix is not a valid command
> > 
> > C:\>aids-windows.bat stories
> > stories is not a valid command
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Am I missing something? aids-windows.bat register works, but that's about it.
> 
> The platform is a required param. You need to point it to the right website. I should have made it clearer, my bad.
> 
> ```
> aids-windows.bat all -p aid
> ```

```
C:\>aids-windows.bat all -p aid
Traceback (most recent call last):
  File "c:\Python38\Scripts\aids-windows.bat", line 4, in <module>
    get_command()
  File "c:\python38\lib\site-packages\aids\manage.py", line 47, in get_command
    platform = getattr(commands, cmd.platform)()
  File "c:\python38\lib\site-packages\aids\commands.py", line 34, in __init__
    super().__init__()
  File "c:\python38\lib\site-packages\aids\app\client.py", line 161, in __init__
    super().__init__()
  File "c:\python38\lib\site-packages\aids\app\client.py", line 106, in __init__
    settings.headers.update(self.headers.generate())
  File "c:\python38\lib\site-packages\aids\app\client.py", line 30, in generate
    return re.sub(settings.headers, 'Chrome/%d.', f'Chrome/{random.randint(60,90)}.')
  File "c:\python38\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\python38\lib\re.py", line 294, in _compile
    return _cache[type(pattern), pattern, flags]
TypeError: unhashable type: 'dict'
```

**Comment by Moist-Cat** [comment]
pip3 install fake-headers

**Comment by God-damnit-all** [comment]
> ```
> pip3 install fake-headers
> ```

```
C:\>aids-windows.bat all -p aid
Traceback (most recent call last):
  File "c:\Python38\Scripts\aids-windows.bat", line 4, in <module>
    get_command()
  File "c:\python38\lib\site-packages\aids\manage.py", line 47, in get_command
    platform = getattr(commands, cmd.platform)()
  File "c:\python38\lib\site-packages\aids\commands.py", line 34, in __init__
    super().__init__()
  File "c:\python38\lib\site-packages\aids\app\client.py", line 161, in __init__
    super().__init__()
  File "c:\python38\lib\site-packages\aids\app\client.py", line 109, in __init__
    self._initial_logging()
  File "c:\python38\lib\site-packages\aids\app\client.py", line 115, in _initial_logging
    log('init', f'{self.__class__.__name__} successfully initialized.')
  File "c:\python38\lib\site-packages\aids\app\writelogs.py", line 25, in log
    if os.stat(LOG_FILE).st_size > 5000000:
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/dev/stdout'
```

**Comment by Moist-Cat** [comment]
pip3 install --force-reinstall aids

**Comment by God-damnit-all** [comment]
> ```
> pip3 install --force-reinstall aids
> ```
```
C:\>aids-windows.bat all -p aid
2021-11-07 14:02:22.926862 [init] ---------------INIT---------------
Aid successfully initialized.

2021-11-07 14:02:24.346880 [log] User "###############" sucessfully logged into AID

2021-11-07 14:02:24.787086 [log] Loaded story: "################"

2021-11-07 14:02:24.954477 [log] Loaded story: "################"

2021-11-07 14:02:25.156723 [log] Loaded story: "############"

2021-11-07 14:02:25.368410 [log] Loaded story: "##########################################"

2021-11-07 14:02:25.597556 [log] Loaded story: "#################################################"

2021-11-07 14:02:25.747991 [log] Loaded story: "######################"

2021-11-07 14:02:25.928205 [log] Loaded story: "################"

2021-11-07 14:02:26.069626 [log] Loaded story: "################"

2021-11-07 14:02:26.214376 [log] Loaded story: "################"

2021-11-07 14:02:26.525296 [log] Loaded story: "#################"

Traceback (most recent call last):
  File "c:\Python38\Scripts\aids-windows.bat", line 4, in <module>
    get_command()
  File "c:\python38\lib\site-packages\aids\manage.py", line 52, in get_command
    command(*required_args)
  File "c:\python38\lib\site-packages\aids\commands.py", line 55, in all
    self.stories(title, min_act)
  File "c:\python38\lib\site-packages\aids\commands.py", line 43, in stories
    self.adventures.dump()
  File "c:\python38\lib\site-packages\aids\app\models.py", line 132, in dump
    with open(self.default_backups_file, "w") as file:
OSError: [Errno 22] Invalid argument: 'C:\\Python38\\Lib\\site-packages\\aids\\backups\\story_2021-11-07 14:02:22.893873.json'
```

**Comment by Moist-Cat** [comment]
Yeah, because the paths in windows are different.
But didn't it download the .json?
The stories should have been downloaded.

If there is a .json file, run:

    aids-windows.bat alltohtml

**Comment by God-damnit-all** [comment]
Thanks again.

**Comment by God-damnit-all** [comment]
@Moist-Cat Just a heads-up, it seems AI Dungeon removed world info hiding a few days ago (except for the official ones, of course...), so backing that up might be possible again.

**Comment by Moist-Cat** [comment]
@ImportTaste
My fix also included downloading WI for each scenario. So, If they didn't change the backend, you should still be able to save it.

**Comment by rnetiks** [comment]
@Moist-Cat 
```
2022-01-17 07:07:38.943822 [log] All stories downloaded

Traceback (most recent call last):
  File "C:\Users\Shirayuki\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Shirayuki\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shirayuki\AppData\Local\Programs\Python\Python38\lib\site-packages\aids\__main__.py", line 3, in <module>
    get_command()
  File "C:\Users\Shirayuki\AppData\Local\Programs\Python\Python38\lib\site-packages\aids\manage.py", line 52, in get_command
    command(*required_args)
  File "C:\Users\Shirayuki\AppData\Local\Programs\Python\Python38\lib\site-packages\aids\commands.py", line 44, in stories
    self.th.story_to_html()
  File "C:\Users\Shirayuki\AppData\Local\Programs\Python\Python38\lib\site-packages\aids\to_html.py", line 66, in story_to_html
    htmlfile.write(
UnicodeEncodeError: 'cp932' codec can't encode character '\ufffc' in position 846: illegal multibyte sequence
```
Some default encodings may not be able to write the files, like in this instance cp932 being the case.
See the PR on the Main
